/**
 * CSS custom-properties emitter for design-token-sync.
 * Pure function — no I/O, no side effects.
 */

/**
 * Emits a CSS file with :root custom properties from a brand config.
 * @param {object} cfg - Brand config (palette, typography, …)
 * @returns {string} CSS file content
 */
export function emitCss(cfg) {
  const lines = [];

  lines.push('/* Generated by atelier design-token-sync. Do not edit by hand. */');
  lines.push(':root {');

  // Palette — one --color-<name> per entry
  const palette = cfg.palette ?? {};
  for (const [name, value] of Object.entries(palette)) {
    lines.push(`  --color-${name}: ${value};`);
  }

  // Typography — only emit keys that have a truthy value
  const typography = cfg.typography ?? {};
  const fontKeys = ['display', 'body', 'mono'];
  for (const key of fontKeys) {
    if (typography[key]) {
      lines.push(`  --font-${key}: "${typography[key]}";`);
    }
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
