/**
 * TypeScript declarations emitter for design-token-sync.
 * Pure function — no I/O, no side effects.
 */

/**
 * Emits a .d.ts file with ColorName/FontName union types and palette consts.
 * @param {object} cfg - Brand config (palette, typography, …)
 * @returns {string} TypeScript declarations file content
 */
export function emitDts(cfg) {
  const palette = cfg.palette ?? {};
  const typography = cfg.typography ?? {};

  const lines = [];

  lines.push('// Generated by atelier design-token-sync. Do not edit by hand.');

  // ColorName union
  const colorKeys = Object.keys(palette);
  if (colorKeys.length === 0) {
    lines.push('export type ColorName = never;');
  } else {
    const union = colorKeys.map((k) => `'${k}'`).join(' | ');
    lines.push(`export type ColorName = ${union};`);
  }

  // FontName union — only keys with truthy values
  const fontKeys = Object.entries(typography)
    .filter(([, v]) => v)
    .map(([k]) => k);
  if (fontKeys.length === 0) {
    lines.push('export type FontName = never;');
  } else {
    const union = fontKeys.map((k) => `'${k}'`).join(' | ');
    lines.push(`export type FontName = ${union};`);
  }

  // export const per palette entry
  for (const [name, value] of Object.entries(palette)) {
    lines.push(`export const ${name} = '${value}';`);
  }

  lines.push('');

  return lines.join('\n');
}
