/**
 * Helpers shared by the design-token-sync emitters: safe serialization of
 * brand values into CSS, JavaScript and TypeScript source, font stack
 * parsing, and identifier derivation. Pure functions, no I/O.
 *
 * Every emitter goes through these helpers, so a brand.json value can never
 * break out of a string literal or a declaration in any generated file.
 */

export const GENERATED_BY = 'Generated by atelier design-token-sync. Do not edit by hand.';

/** Font slots in the order they are emitted. Extra keys follow in insertion order. */
export const FONT_SLOTS = ['display', 'body', 'mono'];

/** Generic family appended to a Tailwind font stack that has none. */
export const SLOT_GENERIC = { display: 'sans-serif', body: 'sans-serif', mono: 'monospace' };

/**
 * Keywords left unquoted in a font-family list. Quoting a generic family
 * turns it into a family name that matches no font.
 */
const GENERIC_FAMILIES = new Set([
  'serif', 'sans-serif', 'monospace', 'cursive', 'fantasy', 'system-ui',
  'ui-serif', 'ui-sans-serif', 'ui-monospace', 'ui-rounded', 'math', 'emoji', 'fangsong',
  // Vendor system-font keywords; Safari ignores -apple-system once quoted.
  '-apple-system', 'blinkmacsystemfont',
]);

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * Names that cannot be an exported binding in an ES module (strict mode), plus
 * globals that TypeScript refuses to redeclare.
 */
const RESERVED = new Set(
  ('break case catch class const continue debugger default delete do else enum export extends '
    + 'false finally for function if import in instanceof new null return super switch this throw '
    + 'true try typeof var void while with yield let static implements interface package private '
    + 'protected public await arguments eval undefined NaN Infinity globalThis').split(' '),
);

// ---------------------------------------------------------------------------
// CSS
// ---------------------------------------------------------------------------

/**
 * Serialize a value as a double-quoted CSS string. Escapes `"` and `\`,
 * encodes control characters as hex escapes, and escapes `<` so the result
 * stays inert when a stylesheet is inlined into a `<style>` element.
 * @param {unknown} value
 * @returns {string}
 */
export function cssString(value) {
  let out = '"';
  for (const ch of String(value)) {
    const cp = ch.codePointAt(0);
    if (ch === '"' || ch === '\\') out += `\\${ch}`;
    else if (cp === 0) out += '\uFFFD';
    else if (cp < 0x20 || cp === 0x7f || ch === '<') out += `\\${cp.toString(16)} `;
    else out += ch;
  }
  return `${out}"`;
}

/**
 * Escape text for use inside a CSS identifier, such as the `<name>` part of
 * `--color-<name>`. Letters, digits, `-`, `_` and non-ASCII pass through;
 * anything else becomes a hex escape.
 * @param {unknown} value
 * @returns {string}
 */
export function cssIdent(value) {
  let out = '';
  for (const ch of String(value)) {
    const cp = ch.codePointAt(0);
    if (/[A-Za-z0-9_-]/.test(ch) || cp >= 0x80) out += ch;
    else if (cp === 0) out += '\uFFFD';
    else out += `\\${cp.toString(16)} `;
  }
  return out;
}

/** Characters a color value may contain: hex, names, and color functions. */
const SAFE_COLOR = /^[A-Za-z0-9#.,%()/+\- ]+$/;

/**
 * Return a palette value that is safe to place in a CSS declaration, or throw.
 * brand.json only allows hex colors; this guards callers that pass a config to
 * the emitters directly. Named colors and functions such as rgb() are accepted.
 * @param {unknown} value
 * @param {string} where - Field name used in the error, e.g. `palette.bg`.
 * @returns {string}
 */
export function cssColor(value, where) {
  const s = typeof value === 'string' ? value.trim() : '';
  let depth = 0;
  let balanced = true;
  for (const ch of s) {
    if (ch === '(') depth++;
    else if (ch === ')' && --depth < 0) balanced = false;
  }
  if (!s || !SAFE_COLOR.test(s) || !balanced || depth !== 0) {
    throw new TypeError(`${where} must be a CSS color such as #110f1b, got ${JSON.stringify(value)}`);
  }
  return s;
}

// ---------------------------------------------------------------------------
// Font stacks
// ---------------------------------------------------------------------------

/** Undo CSS string escapes: `\"`, `\\`, hex escapes, escaped newlines. */
function cssUnescape(s) {
  return s.replace(/\\(?:([0-9a-fA-F]{1,6})[ \t\n]?|(\r\n|[\n\r\f])|([\s\S]))/g, (_, hex, nl, ch) => {
    if (hex) {
      const cp = parseInt(hex, 16);
      return cp === 0 || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff) ? '\uFFFD' : String.fromCodePoint(cp);
    }
    if (nl) return '';
    return ch;
  });
}

/**
 * Parse a CSS font-family value such as `Silkscreen, 'Courier New', monospace`
 * into its families. Commas inside quotes do not split. A fully quoted entry
 * is a family name even when it spells a generic (`"serif"`); an unquoted
 * entry is a generic when it is one of the generic keywords. Anything else,
 * including stray quotes, is taken literally as a family name, so the
 * serializer can quote it safely.
 *
 * @param {unknown} value
 * @returns {{ name: string, generic: boolean }[]}
 */
export function parseFontFamilies(value) {
  const src = String(value ?? '');
  const raw = [];
  let cur = '';
  let quote = null;
  for (let i = 0; i < src.length; i++) {
    const c = src[i];
    if (quote) {
      if (c === '\\' && i + 1 < src.length) {
        cur += c + src[++i];
        continue;
      }
      if (c === quote) quote = null;
      cur += c;
    } else if (c === '"' || c === "'") {
      quote = c;
      cur += c;
    } else if (c === ',') {
      raw.push(cur);
      cur = '';
    } else {
      cur += c;
    }
  }
  raw.push(cur);

  const families = [];
  for (const entry of raw.map((e) => e.trim())) {
    if (!entry) continue;
    // A complete quoted string, or one left open at the end of the value
    // (CSS closes a string at end of input).
    const quoted = /^(["'])((?:\\[\s\S]|(?!\1)[^\\])*)(?:\1)?$/.exec(entry);
    if (quoted) {
      const name = cssUnescape(quoted[2]);
      if (name) families.push({ name, generic: false });
      continue;
    }
    const name = entry.replace(/\s+/g, ' ');
    families.push({ name, generic: GENERIC_FAMILIES.has(name.toLowerCase()) });
  }
  return families;
}

/**
 * Serialize one family for CSS: generics stay bare, names are quoted.
 * @param {{ name: string, generic: boolean }} family
 * @returns {string}
 */
export function formatFamily(family) {
  return family.generic ? family.name : cssString(family.name);
}

/**
 * The typography entries every emitter uses: known slots first (display, body,
 * mono), then any other keys, skipping empty values and stacks with no family.
 * @param {object} cfg - Brand config.
 * @returns {{ key: string, raw: string, families: { name: string, generic: boolean }[], css: string }[]}
 */
export function fontEntries(cfg) {
  const typography = cfg?.typography ?? {};
  const keys = [
    ...FONT_SLOTS.filter((k) => Object.hasOwn(typography, k)),
    ...Object.keys(typography).filter((k) => !FONT_SLOTS.includes(k)),
  ];
  const entries = [];
  for (const key of keys) {
    const value = typography[key];
    if (!value) continue;
    const families = parseFontFamilies(value);
    if (families.length === 0) continue;
    entries.push({ key, raw: String(value), families, css: families.map(formatFamily).join(', ') });
  }
  return entries;
}

/**
 * The palette entries every emitter uses, with each value checked by cssColor.
 * @param {object} cfg - Brand config.
 * @returns {[string, string][]}
 */
export function paletteEntries(cfg) {
  return Object.entries(cfg?.palette ?? {}).map(([key, value]) => [key, cssColor(value, `palette.${key}`)]);
}

// ---------------------------------------------------------------------------
// JavaScript and TypeScript
// ---------------------------------------------------------------------------

/**
 * Serialize a value as a single-quoted JavaScript (and TypeScript) string
 * literal. Built on JSON.stringify, so every quote, backslash, control
 * character and lone surrogate is escaped; `<` is escaped too so the literal
 * stays inert inside an inline `<script>`.
 * @param {unknown} value
 * @returns {string}
 */
export function jsString(value) {
  const body = JSON.stringify(String(value)).slice(1, -1);
  // JSON escapes every `"` as `\"`; a single-quoted literal needs `'` escaped instead.
  return `'${body.replace(/\\"/g, '"').replace(/'/g, "\\'").replace(/</g, '\\u003c')}'`;
}

/**
 * An object-literal key: bare when it is an identifier, quoted otherwise.
 * `__proto__` is written as a computed key in JS so it stays an own property.
 * @param {string} name
 * @param {{ ts?: boolean }} [opts] - ts: key of a TypeScript type literal.
 * @returns {string}
 */
export function propKey(name, { ts = false } = {}) {
  if (name === '__proto__') return ts ? jsString(name) : `[${jsString(name)}]`;
  return IDENTIFIER.test(name) ? name : jsString(name);
}

/** True when `name` can be used as an exported `const` binding. */
export function isSafeIdentifier(name) {
  return IDENTIFIER.test(name) && !RESERVED.has(name);
}

/**
 * Map palette keys to exported binding names. A key that is already a valid,
 * non-reserved identifier keeps its name. Other keys are camelCased on their
 * separators (`brand-500` -> `brand500`, `brand-primary` -> `brandPrimary`),
 * given a leading `_` when they would start with a digit, and a trailing `_`
 * when the result is reserved or already taken (`default` -> `default_`).
 *
 * @param {string[]} keys - Palette keys in emit order.
 * @param {Iterable<string>} [taken] - Names already exported by the module.
 * @returns {Map<string, string>} key -> identifier, in key order.
 */
export function exportNames(keys, taken = []) {
  const used = new Set(taken);
  const names = new Map();
  for (const key of keys) {
    if (isSafeIdentifier(key) && !used.has(key)) {
      names.set(key, key);
      used.add(key);
    }
  }
  const out = new Map();
  for (const key of keys) {
    if (!names.has(key)) {
      let id = key
        .split(/[^A-Za-z0-9_$]+/)
        .filter(Boolean)
        .map((part, i) => (i === 0 ? part : part[0].toUpperCase() + part.slice(1)))
        .join('');
      if (!id || /^[0-9]/.test(id)) id = `_${id}`;
      while (RESERVED.has(id) || used.has(id)) id += '_';
      names.set(key, id);
      used.add(id);
    }
    out.set(key, names.get(key));
  }
  return out;
}

// ---------------------------------------------------------------------------
// Color conversion
// ---------------------------------------------------------------------------

/**
 * Convert #rgb, #rgba, #rrggbb or #rrggbbaa to Figma's { r, g, b, a } floats
 * in the range 0 to 1 (rounded to 6 decimals).
 * @param {string} hex
 * @returns {{ r: number, g: number, b: number, a: number } | null} null when not a hex color.
 */
export function hexToRgba(hex) {
  const m = /^#([0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/.exec(String(hex).trim());
  if (!m) return null;
  let digits = m[1];
  if (digits.length <= 4) digits = [...digits].map((d) => d + d).join('');
  if (digits.length === 6) digits += 'ff';
  const channel = (i) => Math.round((parseInt(digits.slice(i, i + 2), 16) / 255) * 1e6) / 1e6;
  return { r: channel(0), g: channel(2), b: channel(4), a: channel(6) };
}
