/**
 * Tailwind config emitter for design-token-sync.
 * Pure function — no I/O, no side effects.
 */

/** Fallback generic families by font slot. */
const GENERIC_FAMILY = {
  display: 'sans-serif',
  body: 'sans-serif',
  mono: 'monospace',
};

/**
 * Emits a Tailwind config file (ESM, default export) from a brand config.
 * @param {object} cfg - Brand config (palette, typography, …)
 * @returns {string} JavaScript file content
 */
export function emitTailwind(cfg) {
  const palette = cfg.palette ?? {};
  const typography = cfg.typography ?? {};

  // Build colors block
  const colorLines = Object.entries(palette).map(
    ([name, value]) => `        ${name}: '${value}'`,
  );

  // Build fontFamily block — only emit present keys
  const fontKeys = ['display', 'body', 'mono'];
  const fontLines = fontKeys
    .filter((k) => typography[k])
    .map((k) => {
      const family = GENERIC_FAMILY[k] ?? 'sans-serif';
      return `        ${k}: ['${typography[k]}', '${family}']`;
    });

  const lines = [
    '// Generated by atelier design-token-sync. Do not edit by hand.',
    'export default {',
    '  theme: {',
    '    extend: {',
    '      colors: {',
    ...colorLines.map((l) => l + ','),
    '      },',
    '      fontFamily: {',
    ...fontLines.map((l) => l + ','),
    '      }',
    '    }',
    '  }',
    '};',
    '',
  ];

  return lines.join('\n');
}
