import { describe, it, expect } from 'vitest';
import { emitCss } from '../../plugins/atelier/skills/design-token-sync/emitters/css.mjs';
import { pluginRequire } from '../helpers/plugin-deps.mjs';

const postcss = pluginRequire('postcss');

const fixture = {
  brand: { studio: 'goneIdle' },
  palette: { bg: '#110f1b', terra: '#e07a5f' },
  typography: { display: 'Silkscreen', body: 'Geist', mono: 'Geist Mono' },
};

/** Parse with postcss and return the declarations of the single :root rule. */
function rootDecls(css) {
  const ast = postcss.parse(css);
  const rules = ast.nodes.filter((n) => n.type === 'rule');
  expect(rules).toHaveLength(1);
  expect(rules[0].selector).toBe(':root');
  return Object.fromEntries(rules[0].nodes.filter((n) => n.type === 'decl').map((d) => [d.prop, d.value]));
}

describe('emitCss', () => {
  it('emits :root { with palette custom props', () => {
    const out = emitCss(fixture);
    expect(out).toContain(':root {');
    expect(out).toContain('  --color-bg: #110f1b;');
    expect(out).toContain('  --color-terra: #e07a5f;');
  });

  it('emits typography --font-* props', () => {
    const out = emitCss(fixture);
    expect(out).toContain('  --font-display: "Silkscreen";');
    expect(out).toContain('  --font-body: "Geist";');
    expect(out).toContain('  --font-mono: "Geist Mono";');
  });

  it('ends with closing brace and newline', () => {
    const out = emitCss(fixture);
    expect(out.trimEnd()).toMatch(/\}$/);
    expect(out).toMatch(/\n$/);
  });

  it('starts with the generated-by block comment', () => {
    expect(emitCss(fixture).split('\n')[0]).toBe('/* Generated by atelier design-token-sync. Do not edit by hand. */');
  });

  it('is deterministic: same input yields identical output', () => {
    expect(emitCss(fixture)).toBe(emitCss(fixture));
  });

  it('emits a font stack as a font-family list, not one quoted string', () => {
    // The /brand-init example stack.
    const out = emitCss({ palette: { bg: '#000' }, typography: { body: "Silkscreen, 'Courier New', monospace" } });
    expect(out).toContain('  --font-body: "Silkscreen", "Courier New", monospace;');
  });

  it('keeps generic families bare and re-quotes already quoted names', () => {
    const out = emitCss({
      palette: { bg: '#000' },
      typography: { body: 'monospace', display: '"Geist", system-ui, sans-serif', mono: "'serif'" },
    });
    expect(out).toContain('  --font-body: monospace;');
    expect(out).toContain('  --font-display: "Geist", system-ui, sans-serif;');
    // A quoted "serif" is a family name, not the generic.
    expect(out).toContain('  --font-mono: "serif";');
  });

  it('quotes digit-bearing family names', () => {
    const out = emitCss({ palette: { bg: '#000' }, typography: { body: 'Source Sans 3', display: 'Press Start 2P' } });
    expect(out).toContain('--font-body: "Source Sans 3";');
    expect(out).toContain('--font-display: "Press Start 2P";');
  });

  it('cannot be broken out of by a typography value', () => {
    const payload = 'Inter"; } body { display: none } :root { --x: "';
    const decls = rootDecls(emitCss({ palette: { bg: '#000' }, typography: { body: payload } }));
    expect(decls['--font-body']).toBe(`"Inter\\"; } body { display: none } :root { --x: \\""`);
  });

  it('escapes a trailing backslash, newlines and < so the stylesheet still parses', () => {
    const css = emitCss({ palette: { bg: '#000' }, typography: { body: 'Font\\', display: '"A\nB\u0001"', mono: '</style>' } });
    const decls = rootDecls(css);
    expect(decls['--font-body']).toBe('"Font\\\\"');
    expect(decls['--font-display']).toBe('"A\\a B\\1 "');
    expect(decls['--font-mono']).toBe('"\\3c /style>"');
    expect(css).not.toContain('</style>');
  });

  it('handles schema-valid hyphenated and reserved-word palette keys', () => {
    const decls = rootDecls(emitCss({ palette: { 'brand-500': '#e07a5f', default: '#fff', class: '#000' }, typography: { body: 'X' } }));
    expect(decls['--color-brand-500']).toBe('#e07a5f');
    expect(decls['--color-default']).toBe('#fff');
    expect(decls['--color-class']).toBe('#000');
  });

  it('escapes palette keys that are not CSS identifier characters', () => {
    const css = emitCss({ palette: { 'a b;c': '#fff' }, typography: {} });
    expect(css).toContain('--color-a\\20 b\\3b c: #fff;');
    rootDecls(css);
  });

  it('rejects palette values that could end the declaration', () => {
    expect(() => emitCss({ palette: { bg: 'red; } body { display:none }' } })).toThrow(/palette\.bg must be a CSS color/);
    expect(() => emitCss({ palette: { bg: 'rgb(1,2,3' } })).toThrow(TypeError);
    expect(() => emitCss({ palette: { bg: '' } })).toThrow(TypeError);
    expect(() => emitCss({ palette: { bg: 42 } })).toThrow(TypeError);
  });

  it('accepts non-hex CSS colors from direct callers', () => {
    expect(emitCss({ palette: { a: 'rgb(0 0 0 / 50%)', b: 'rebeccapurple' } })).toContain('--color-a: rgb(0 0 0 / 50%);');
  });

  it('skips empty and whitespace-only typography values', () => {
    const out = emitCss({ palette: { bg: '#000' }, typography: { body: ' , ', display: '' } });
    expect(out).not.toContain('--font-');
  });

  it('handles a config with no palette or typography', () => {
    expect(emitCss({})).toBe('/* Generated by atelier design-token-sync. Do not edit by hand. */\n:root {\n}\n');
  });
});
