import * as nodeModule from 'node:module';
import { describe, it, expect } from 'vitest';
import { emitDts } from '../../plugins/atelier/skills/design-token-sync/emitters/dts.mjs';
import { emitJs } from '../../plugins/atelier/skills/design-token-sync/emitters/js.mjs';
import { pluginRequire } from '../helpers/plugin-deps.mjs';

const acorn = pluginRequire('acorn');
// Node's TypeScript parser (22.13+ / 23.2+). It rejects syntax errors, which
// is what these tests need; older Node skips the full-file parse checks.
const { stripTypeScriptTypes } = nodeModule;
const hasTsParser = typeof stripTypeScriptTypes === 'function';

const fixture = {
  brand: { studio: 'goneIdle' },
  palette: { bg: '#110f1b', terra: '#e07a5f' },
  typography: { display: 'Silkscreen', body: 'Geist', mono: 'Geist Mono' },
};

const edge = {
  palette: {
    bg: '#110f1b',
    'brand-500': '#e07a5f',
    'brand-primary': '#000',
    brandPrimary: '#fff',
    default: '#123',
    class: '#456',
    let: '#789',
    public: '#abc',
    colors: '#def',
    a_1: '#111',
    Object: '#fed',
  },
  typography: { body: "Silkscreen, 'Courier New', monospace", display: 'Press Start 2P' },
};

const declaredConsts = (dts) => [...dts.matchAll(/^export declare const ([^:]+):/gm)].map((m) => m[1]);

describe('emitDts', () => {
  it('starts with the generated-by line comment', () => {
    expect(emitDts(fixture).split('\n')[0]).toBe('// Generated by atelier design-token-sync. Do not edit by hand.');
  });

  it('exports ColorName union with all palette keys', () => {
    expect(emitDts(fixture)).toContain("export type ColorName = 'bg' | 'terra';");
  });

  it('exports FontName union with present typography keys', () => {
    expect(emitDts(fixture)).toContain("export type FontName = 'display' | 'body' | 'mono';");
  });

  it('declares one ambient const per palette entry', () => {
    const out = emitDts(fixture);
    expect(out).toContain("export declare const bg: '#110f1b';");
    expect(out).toContain("export declare const terra: '#e07a5f';");
  });

  it('declares colors and fonts objects with literal types', () => {
    const out = emitDts(fixture);
    expect(out).toContain("export declare const colors: {\n  readonly bg: '#110f1b';\n  readonly terra: '#e07a5f';\n};");
    expect(out).toContain(`  readonly display: '"Silkscreen"';`);
  });

  it('handles empty palette with ColorName = never', () => {
    const out = emitDts({ palette: {}, typography: {} });
    expect(out).toContain('export type ColorName = never;');
    expect(out).toContain('export type FontName = never;');
    expect(out).toContain('export declare const colors: {};');
  });

  it('derives safe identifiers for hyphenated and reserved-word keys', () => {
    const out = emitDts(edge);
    expect(declaredConsts(out)).toEqual([
      'colors', 'fonts', 'bg', 'brand500', 'brandPrimary_', 'brandPrimary', 'default_', 'class_', 'let_', 'public_', 'colors_', 'a_1',
      'Object_',
    ]);
    expect(out).toContain("/** colors['Object'] */\nexport declare const Object_: '#fed';");
    expect(out).toContain("/** colors['brand-500'] */\nexport declare const brand500: '#e07a5f';");
    expect(out).toContain("  readonly 'brand-500': '#e07a5f';");
    expect(out).toContain('  readonly default: ');
  });

  it('every declared const is a legal ES module binding', () => {
    for (const name of declaredConsts(emitDts(edge))) {
      expect(() => acorn.parse(`export const ${name} = 1;`, { ecmaVersion: 'latest', sourceType: 'module' })).not.toThrow();
    }
  });

  it.skipIf(!hasTsParser)('parses as TypeScript for schema-valid edge keys', () => {
    expect(() => stripTypeScriptTypes(emitDts(edge))).not.toThrow();
    expect(() => stripTypeScriptTypes(emitDts(fixture))).not.toThrow();
  });

  it.skipIf(!hasTsParser)('the TypeScript check catches the old invalid output', () => {
    expect(() => stripTypeScriptTypes("export const brand-500 = '#e07a5f';")).toThrow();
    expect(() => stripTypeScriptTypes("export const default = '#e07a5f';")).toThrow();
  });

  it('escapes quotes, backslashes and comment terminators in keys and values', () => {
    const cfg = { palette: { "it's*/": 'rgb(1, 2, 3)' }, typography: { body: "O'Brien\\" } };
    const out = emitDts(cfg);
    expect(out).toContain("readonly 'it\\'s*/': 'rgb(1, 2, 3)';");
    expect(out).toContain("/** colors['it\\'s*\\/'] */");
    expect(out).toContain(`readonly body: '"O\\'Brien\\\\\\\\"';`);
    if (hasTsParser) expect(() => stripTypeScriptTypes(out)).not.toThrow();
  });

  it('declares exactly the names tokens.js exports, with the same values', async () => {
    for (const cfg of [fixture, edge]) {
      const mod = await import(`data:text/javascript,${encodeURIComponent(emitJs(cfg))}`);
      const dts = emitDts(cfg);
      expect(declaredConsts(dts).sort()).toEqual(Object.keys(mod).sort());
      for (const name of declaredConsts(dts)) {
        if (typeof mod[name] !== 'string') continue;
        const literal = new RegExp(`^export declare const ${name.replace(/\$/g, '\\$')}: '([^']*)';$`, 'm').exec(dts)[1];
        expect(mod[name]).toBe(literal);
      }
    }
  });
});
