import { describe, it, expect } from 'vitest';
import { emitJs } from '../../plugins/atelier/skills/design-token-sync/emitters/js.mjs';

async function load(src) {
  return import(`data:text/javascript,${encodeURIComponent(src)}`);
}

describe('emitJs', () => {
  it('starts with the generated-by line comment', () => {
    expect(emitJs({ palette: { bg: '#000' } }).split('\n')[0]).toBe('// Generated by atelier design-token-sync. Do not edit by hand.');
  });

  it('exports frozen colors and fonts objects plus one const per color', async () => {
    const mod = await load(emitJs({
      palette: { bg: '#110f1b', terra: '#e07a5f' },
      typography: { display: 'Silkscreen', body: "Inter, 'Helvetica Neue', sans-serif" },
    }));
    expect(mod.colors).toEqual({ bg: '#110f1b', terra: '#e07a5f' });
    expect(mod.fonts).toEqual({ display: '"Silkscreen"', body: '"Inter", "Helvetica Neue", sans-serif' });
    expect(Object.isFrozen(mod.colors)).toBe(true);
    expect(Object.isFrozen(mod.fonts)).toBe(true);
    expect(mod.bg).toBe('#110f1b');
    expect(mod.terra).toBe('#e07a5f');
  });

  it('keeps every palette key in colors and gives each a safe named export', async () => {
    const palette = { 'brand-500': '#e07a5f', default: '#fff', class: '#000', fonts: '#111', '9lives': '#222' };
    const mod = await load(emitJs({ palette }));
    expect(mod.colors).toEqual(palette);
    expect(mod.brand500).toBe('#e07a5f');
    expect(mod.default_).toBe('#fff');
    expect(mod.class_).toBe('#000');
    expect(mod.fonts_).toBe('#111');
    expect(mod._9lives).toBe('#222');
    expect(mod.fonts).toEqual({});
  });

  it('cannot be broken out of by a key or value', async () => {
    const key = "x'; globalThis.pwned = 1; '";
    const mod = await load(emitJs({ palette: { [key]: '#fff' }, typography: { body: "a'; globalThis.pwned = 2; '</script>" } }));
    expect(globalThis.pwned).toBeUndefined();
    expect(mod.colors[key]).toBe('#fff');
    expect(emitJs({ typography: { body: '</script>' } })).not.toContain('</script>');
  });
});
