import { describe, it, expect } from 'vitest';
import { emitTailwind } from '../../plugins/atelier/skills/design-token-sync/emitters/tailwind.mjs';

const fixture = {
  brand: { studio: 'goneIdle' },
  palette: { bg: '#110f1b', terra: '#e07a5f' },
  typography: { display: 'Silkscreen', body: 'Geist', mono: 'Geist Mono' },
};

async function load(src) {
  return (await import(`data:text/javascript,${encodeURIComponent(src)}`)).default;
}

describe('emitTailwind', () => {
  it('returns an export default string with the generated-by header', () => {
    const out = emitTailwind(fixture);
    expect(typeof out).toBe('string');
    expect(out.split('\n')[0]).toBe('// Generated by atelier design-token-sync. Do not edit by hand.');
    expect(out).toContain('export default');
  });

  it('contains palette colors', () => {
    const out = emitTailwind(fixture);
    expect(out).toContain("bg: '#110f1b'");
    expect(out).toContain("terra: '#e07a5f'");
  });

  it('contains CSS-quoted fontFamily entries with a generic fallback', () => {
    const out = emitTailwind(fixture);
    expect(out).toContain(`display: ['"Silkscreen"', 'sans-serif']`);
    expect(out).toContain(`body: ['"Geist"', 'sans-serif']`);
    expect(out).toContain(`mono: ['"Geist Mono"', 'monospace']`);
  });

  it('is valid JavaScript with correct theme structure', async () => {
    const cfg = await load(emitTailwind(fixture));
    expect(cfg.theme.extend.colors.bg).toBe('#110f1b');
    expect(cfg.theme.extend.fontFamily.mono).toEqual(['"Geist Mono"', 'monospace']);
  });

  it('quotes hyphenated keys and still imports (reserved words stay valid property names)', async () => {
    const palette = { 'brand-500': '#e07a5f', default: '#fff', class: '#000', a_1: '#111' };
    const out = emitTailwind({ palette, typography: { body: 'X' } });
    expect(out).toContain("'brand-500': '#e07a5f'");
    const cfg = await load(out);
    expect(cfg.theme.extend.colors).toEqual(palette);
  });

  it('keeps __proto__ as an own key instead of setting the prototype', async () => {
    const palette = JSON.parse('{"__proto__":"#123456"}');
    const cfg = await load(emitTailwind({ palette }));
    expect(Object.keys(cfg.theme.extend.colors)).toEqual(['__proto__']);
    expect(Object.getPrototypeOf(cfg.theme.extend.colors)).toBe(Object.prototype);
  });

  it('quotes digit-bearing family names so the joined font-family is valid CSS', async () => {
    const cfg = await load(emitTailwind({ palette: { bg: '#000' }, typography: { display: 'Press Start 2P', body: 'Source Sans 3' } }));
    expect(cfg.theme.extend.fontFamily.display).toEqual(['"Press Start 2P"', 'sans-serif']);
    expect(cfg.theme.extend.fontFamily.body).toEqual(['"Source Sans 3"', 'sans-serif']);
  });

  it('splits a font stack into one entry per family and does not add a second generic', async () => {
    const cfg = await load(emitTailwind({ palette: { bg: '#000' }, typography: { body: "Silkscreen, 'Courier New', monospace" } }));
    expect(cfg.theme.extend.fontFamily.body).toEqual(['"Silkscreen"', '"Courier New"', 'monospace']);
  });

  it('escapes quotes and backslashes in typography values without breaking out of the string', async () => {
    // A hand-edited brand.json can put anything in typography.
    const value = "Arial', '\"]}; sideEffect = 1; ['";
    const cfg = await load(emitTailwind({ palette: { bg: '#110f1b' }, typography: { body: value } }));
    const [family] = cfg.theme.extend.fontFamily.body;
    // One CSS string whose content is the original value.
    expect(family).toBe(`"${value.replace(/"/g, '\\"')}"`);
    expect(globalThis.sideEffect).toBeUndefined();
  });

  it('rejects palette values that would inject CSS through Tailwind', () => {
    expect(() => emitTailwind({ palette: { bg: 'red;} body{display:none' } })).toThrow(/palette\.bg/);
  });

  it('falls back to sans-serif for a font slot it does not know', async () => {
    const cfg = await load(emitTailwind({ palette: { bg: '#000' }, typography: { heading: 'Lora' } }));
    expect(cfg.theme.extend.fontFamily.heading).toEqual(['"Lora"', 'sans-serif']);
  });

  it('handles empty palette and typography', async () => {
    const cfg = await load(emitTailwind({}));
    expect(cfg.theme.extend).toEqual({ colors: {}, fontFamily: {} });
  });
});
